### ISSUE TITLE
Videos fail to load, exception thrown

### ISSUE THREAD

**Issue by Botono** [learningit/plugin.video.thinktv#4]
It appears that PBS has changed their JSON format.  Here's a log entry from Kodi from tonight:

20:13:02 T:4684   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('recommended_encoding',)
                                            Traceback (most recent call last):
                                              File "C:\Users\Aaron\AppData\Roaming\Kodi\addons\plugin.video.thinktv\default.py", line 445, in <module>
                                                elif mode=='GS':  getShow(p('url'))
                                              File "C:\Users\Aaron\AppData\Roaming\Kodi\addons\plugin.video.thinktv\default.py", line 312, in getShow
                                                url = a['recommended_encoding']['url']
                                            KeyError: ('recommended_encoding',)
                                            -->End of Python script error report<--

A quick check of the JSON for this episode shows that there is no 'recommended_encoding' key anywhere.

**Comment by learningit** [comment]
Issue has been corrected. V1.0.21 in my git, repo and a PR issed for kodi.org repo-plugins.

In the future pls use the Kodi.org forum to report issues, I don't always look at notifications here and it's better that everyone can see the problem in the Kodi forum. Thanks!

**Comment by msound** [comment]
@learningit ++

Thank you the super fast response in fixing this. Do you know when the update will be available on the Kodi system. I am still on 1.0.20 and the "Update" button is greyed out.

**Comment by learningit** [comment]
The pull request was merged today. The kodi repo should be in sync tomorrow.
