### ISSUE TITLE
PBS Web Shows

### ISSUE THREAD

**Issue by dirwiz** [learningit/plugin.video.thinktv#6]
The plugin works great.  Is there any chance you can add support for web-shows.  There is a really good BBQ show I'd like to watch.
http://www.pbs.org/food/web-shows/bbq-with-franklin/

**Comment by learningit** [comment]
Not anytime soon. There are other items which need to be fixed/added before this. I'll slide it on the list look at, but am not committing to doing it.

**Comment by dirwiz** [comment]
No worries, thought it would be a cool addition.  Thanks for the great plugin.  I use it like crazy
